"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.version = void 0;
// generated by genversion
const version = '1.6.3';
exports.version = version;
//# sourceMappingURL=version.js.map