import 'text-encoding';
import ChatKitty from './chatkitty';
export * from './call';
export * from './channel';
export * from './chat-session';
export * from './current-user';
export * from './emoji';
export * from './error';
export * from './file';
export * from './keystrokes';
export * from './message';
export * from './model';
export * from './notification';
export * from './observer';
export * from './pagination';
export * from './reaction';
export * from './read-receipt';
export * from './result';
export * from './thread';
export * from './user';
export * from './user-block-list-item';
export * from './user-session';
export declare function multiply(a: number, b: number): Promise<number>;
export default ChatKitty;
