name: Release package

on:
  push:
    branches: [main, beta]

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Generate docs 📚
        run: |
          yarn install --frozen-lockfile
          yarn run example
          yarn run doc:md

      - name: Deploy 🚀
        run: |
          npx semantic-release
          aws s3 cp --recursive --acl public-read docs s3://chatkitty-docs/chatkitty-react-native/docs/src
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
